version: "3"

services:
  web:
    build: ./restaurant
    command: sh -c "bin/init.sh && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./restaurant:/usr/src/restaurant